//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZardabRestaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEAL
    {
        public int ID { get; set; }
        public string MEAL_NAME { get; set; }
        public Nullable<double> MEAL_PRICE { get; set; }
        public string MEAL_INGREDIENTS { get; set; }
        public string MEAL_IMAGE_URL { get; set; }
    }
}
